language: python
python:
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Jianwen-Xu
  password:
    secure: IPuWWKsZb7Dx3XNNXRFle9vx2+zm6MAaSEMi+D4f5tO9NWDvBvOxzLFF14FYyLdITJ+sUWi2L2BwIoSyFfstOonUkmaNtS9zJQXNUNJfV1xIKxo44pPfobg29cLAZY9ryXk9quExPkSx6gWGhxgh+A1zlPhqzmOnbeWKnDmibJycvv0s30BQL1G4M/hoqzQUTuaP1vlvfJ5Jd3Uxu/BgSniW3ttB8FQbXlyi5iymMtkdntZJOxVo3gGKDN2Bq9BKJC9xTPFldxEy01+tWWYMqq/0aiDUF4W/zzXFOhgDCqVISaa1RCyTBKe4xO7v2s9a6QonuMZPUvQHGMnNewdQjuV1Y6wCgXvB63qEm5IgryyLMLc6WRM4q/TJdC9zj2p9evQODyXX0yJ39fgHj3jCVolTdypHml9iZnMloSwp/vYWtnoCJNoxhuc9ca/3wnRho683QMMhj+2vLwPRU+b8i2TmVSwTE8VGmtU4pVJR0i0FOh6x0sgu44xuyjPmzA4+cGrbO6M0HllkwABOHuP0+vh89fNQJUoqvchYyrAXqAeJPOt6ZWdPQIadFZV+GZiTOBNUEcHEQHUZgo6zSrfYClnqr4DeMy42IiqYZhbq9s/HNBj7cMF5AoAN2qKieVpScbT1UmkFRcI7VyevgWjx9aU16rA6bXlPuELeFcT/akQ=
  on:
    tags: true
    repo: Jianwen-Xu/nlon-py
    python: 3.8
